### PR TITLE
[REVIEW] Produce gdf-arrow library

### PR DESCRIPTION
**Pull request by pearu**

### CODE REVIEW

**Comment by britthard** [comment]
rerun tests

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by hhuuggoo** [comment]
this looks good to me except i should have removed some of the tests like 

https://github.com/Quansight/libgdf-arrow/blob/master/tests/filterops_numeric/test_filterops.cu

in #1, so I guess we can remove them here

**Comment by scopatz** [comment]
add to whitelist

**Comment by scopatz** [comment]
LGTM! We should talk about the API changes during our standup today

**Pull request merged**
