### PR TITLE
Reduce Travis Builds on libgdf-arrow from 6 to 2

### PR DESCRIPTION
**Pull request by andersy005**

### CODE REVIEW

**Comment by scopatz** [comment]
This LGTM! Let me know when it is no longer a WIP @andersy005!

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by andersy005** [comment]
Ready to be merged!

**Comment by scopatz** [comment]
run tests

**Comment by scopatz** [comment]
@brittainhard - it looks like gpuCI us now commenting on the PRs, but how do we verify?

**Comment by scopatz** [comment]
add to whitelist

**Comment by scopatz** [comment]
I am going to merge for the benefit of other PRs

**Pull request merged**
